//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sensors", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Sensors : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference1.SensorSteel[] SensorSteelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_sensorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string name_sensorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference1.SensorSteel[] SensorSteel {
            get {
                return this.SensorSteelField;
            }
            set {
                if ((object.ReferenceEquals(this.SensorSteelField, value) != true)) {
                    this.SensorSteelField = value;
                    this.RaisePropertyChanged("SensorSteel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_sensor {
            get {
                return this.id_sensorField;
            }
            set {
                if ((this.id_sensorField.Equals(value) != true)) {
                    this.id_sensorField = value;
                    this.RaisePropertyChanged("id_sensor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_sensor {
            get {
                return this.name_sensorField;
            }
            set {
                if ((object.ReferenceEquals(this.name_sensorField, value) != true)) {
                    this.name_sensorField = value;
                    this.RaisePropertyChanged("name_sensor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SensorSteel", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class SensorSteel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int R01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int R02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference1.Sensors SensorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference1.Steels SteelsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_sensorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_sensor_steelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_steelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int R01 {
            get {
                return this.R01Field;
            }
            set {
                if ((this.R01Field.Equals(value) != true)) {
                    this.R01Field = value;
                    this.RaisePropertyChanged("R01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int R02 {
            get {
                return this.R02Field;
            }
            set {
                if ((this.R02Field.Equals(value) != true)) {
                    this.R02Field = value;
                    this.RaisePropertyChanged("R02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference1.Sensors Sensors {
            get {
                return this.SensorsField;
            }
            set {
                if ((object.ReferenceEquals(this.SensorsField, value) != true)) {
                    this.SensorsField = value;
                    this.RaisePropertyChanged("Sensors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference1.Steels Steels {
            get {
                return this.SteelsField;
            }
            set {
                if ((object.ReferenceEquals(this.SteelsField, value) != true)) {
                    this.SteelsField = value;
                    this.RaisePropertyChanged("Steels");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_sensor {
            get {
                return this.id_sensorField;
            }
            set {
                if ((this.id_sensorField.Equals(value) != true)) {
                    this.id_sensorField = value;
                    this.RaisePropertyChanged("id_sensor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_sensor_steel {
            get {
                return this.id_sensor_steelField;
            }
            set {
                if ((this.id_sensor_steelField.Equals(value) != true)) {
                    this.id_sensor_steelField = value;
                    this.RaisePropertyChanged("id_sensor_steel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_steel {
            get {
                return this.id_steelField;
            }
            set {
                if ((this.id_steelField.Equals(value) != true)) {
                    this.id_steelField = value;
                    this.RaisePropertyChanged("id_steel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Steels", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Steels : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference1.SensorSteel[] SensorSteelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_steelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string name_steelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference1.SensorSteel[] SensorSteel {
            get {
                return this.SensorSteelField;
            }
            set {
                if ((object.ReferenceEquals(this.SensorSteelField, value) != true)) {
                    this.SensorSteelField = value;
                    this.RaisePropertyChanged("SensorSteel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_steel {
            get {
                return this.id_steelField;
            }
            set {
                if ((this.id_steelField.Equals(value) != true)) {
                    this.id_steelField = value;
                    this.RaisePropertyChanged("id_steel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_steel {
            get {
                return this.name_steelField;
            }
            set {
                if ((object.ReferenceEquals(this.name_steelField, value) != true)) {
                    this.name_steelField = value;
                    this.RaisePropertyChanged("name_steel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetlistSensor", ReplyAction="http://tempuri.org/IService1/GetlistSensorResponse")]
        Project.ServiceReference1.Sensors[] GetlistSensor();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetlistSensor", ReplyAction="http://tempuri.org/IService1/GetlistSensorResponse")]
        System.IAsyncResult BeginGetlistSensor(System.AsyncCallback callback, object asyncState);
        
        Project.ServiceReference1.Sensors[] EndGetlistSensor(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetlistSteel", ReplyAction="http://tempuri.org/IService1/GetlistSteelResponse")]
        Project.ServiceReference1.Steels[] GetlistSteel();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetlistSteel", ReplyAction="http://tempuri.org/IService1/GetlistSteelResponse")]
        System.IAsyncResult BeginGetlistSteel(System.AsyncCallback callback, object asyncState);
        
        Project.ServiceReference1.Steels[] EndGetlistSteel(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetlistSensor_Steel", ReplyAction="http://tempuri.org/IService1/GetlistSensor_SteelResponse")]
        Project.ServiceReference1.SensorSteel[] GetlistSensor_Steel(int Id_Sensors, int Id_Steel);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetlistSensor_Steel", ReplyAction="http://tempuri.org/IService1/GetlistSensor_SteelResponse")]
        System.IAsyncResult BeginGetlistSensor_Steel(int Id_Sensors, int Id_Steel, System.AsyncCallback callback, object asyncState);
        
        Project.ServiceReference1.SensorSteel[] EndGetlistSensor_Steel(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Project.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetlistSensorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetlistSensorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Project.ServiceReference1.Sensors[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Project.ServiceReference1.Sensors[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetlistSteelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetlistSteelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Project.ServiceReference1.Steels[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Project.ServiceReference1.Steels[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetlistSensor_SteelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetlistSensor_SteelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Project.ServiceReference1.SensorSteel[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Project.ServiceReference1.SensorSteel[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Project.ServiceReference1.IService1>, Project.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginGetlistSensorDelegate;
        
        private EndOperationDelegate onEndGetlistSensorDelegate;
        
        private System.Threading.SendOrPostCallback onGetlistSensorCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetlistSteelDelegate;
        
        private EndOperationDelegate onEndGetlistSteelDelegate;
        
        private System.Threading.SendOrPostCallback onGetlistSteelCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetlistSensor_SteelDelegate;
        
        private EndOperationDelegate onEndGetlistSensor_SteelDelegate;
        
        private System.Threading.SendOrPostCallback onGetlistSensor_SteelCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetlistSensorCompletedEventArgs> GetlistSensorCompleted;
        
        public event System.EventHandler<GetlistSteelCompletedEventArgs> GetlistSteelCompleted;
        
        public event System.EventHandler<GetlistSensor_SteelCompletedEventArgs> GetlistSensor_SteelCompleted;
        
        public Project.ServiceReference1.Sensors[] GetlistSensor() {
            return base.Channel.GetlistSensor();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetlistSensor(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetlistSensor(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Project.ServiceReference1.Sensors[] EndGetlistSensor(System.IAsyncResult result) {
            return base.Channel.EndGetlistSensor(result);
        }
        
        private System.IAsyncResult OnBeginGetlistSensor(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetlistSensor(callback, asyncState);
        }
        
        private object[] OnEndGetlistSensor(System.IAsyncResult result) {
            Project.ServiceReference1.Sensors[] retVal = this.EndGetlistSensor(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetlistSensorCompleted(object state) {
            if ((this.GetlistSensorCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetlistSensorCompleted(this, new GetlistSensorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetlistSensorAsync() {
            this.GetlistSensorAsync(null);
        }
        
        public void GetlistSensorAsync(object userState) {
            if ((this.onBeginGetlistSensorDelegate == null)) {
                this.onBeginGetlistSensorDelegate = new BeginOperationDelegate(this.OnBeginGetlistSensor);
            }
            if ((this.onEndGetlistSensorDelegate == null)) {
                this.onEndGetlistSensorDelegate = new EndOperationDelegate(this.OnEndGetlistSensor);
            }
            if ((this.onGetlistSensorCompletedDelegate == null)) {
                this.onGetlistSensorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetlistSensorCompleted);
            }
            base.InvokeAsync(this.onBeginGetlistSensorDelegate, null, this.onEndGetlistSensorDelegate, this.onGetlistSensorCompletedDelegate, userState);
        }
        
        public Project.ServiceReference1.Steels[] GetlistSteel() {
            return base.Channel.GetlistSteel();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetlistSteel(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetlistSteel(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Project.ServiceReference1.Steels[] EndGetlistSteel(System.IAsyncResult result) {
            return base.Channel.EndGetlistSteel(result);
        }
        
        private System.IAsyncResult OnBeginGetlistSteel(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetlistSteel(callback, asyncState);
        }
        
        private object[] OnEndGetlistSteel(System.IAsyncResult result) {
            Project.ServiceReference1.Steels[] retVal = this.EndGetlistSteel(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetlistSteelCompleted(object state) {
            if ((this.GetlistSteelCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetlistSteelCompleted(this, new GetlistSteelCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetlistSteelAsync() {
            this.GetlistSteelAsync(null);
        }
        
        public void GetlistSteelAsync(object userState) {
            if ((this.onBeginGetlistSteelDelegate == null)) {
                this.onBeginGetlistSteelDelegate = new BeginOperationDelegate(this.OnBeginGetlistSteel);
            }
            if ((this.onEndGetlistSteelDelegate == null)) {
                this.onEndGetlistSteelDelegate = new EndOperationDelegate(this.OnEndGetlistSteel);
            }
            if ((this.onGetlistSteelCompletedDelegate == null)) {
                this.onGetlistSteelCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetlistSteelCompleted);
            }
            base.InvokeAsync(this.onBeginGetlistSteelDelegate, null, this.onEndGetlistSteelDelegate, this.onGetlistSteelCompletedDelegate, userState);
        }
        
        public Project.ServiceReference1.SensorSteel[] GetlistSensor_Steel(int Id_Sensors, int Id_Steel) {
            return base.Channel.GetlistSensor_Steel(Id_Sensors, Id_Steel);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetlistSensor_Steel(int Id_Sensors, int Id_Steel, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetlistSensor_Steel(Id_Sensors, Id_Steel, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Project.ServiceReference1.SensorSteel[] EndGetlistSensor_Steel(System.IAsyncResult result) {
            return base.Channel.EndGetlistSensor_Steel(result);
        }
        
        private System.IAsyncResult OnBeginGetlistSensor_Steel(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int Id_Sensors = ((int)(inValues[0]));
            int Id_Steel = ((int)(inValues[1]));
            return this.BeginGetlistSensor_Steel(Id_Sensors, Id_Steel, callback, asyncState);
        }
        
        private object[] OnEndGetlistSensor_Steel(System.IAsyncResult result) {
            Project.ServiceReference1.SensorSteel[] retVal = this.EndGetlistSensor_Steel(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetlistSensor_SteelCompleted(object state) {
            if ((this.GetlistSensor_SteelCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetlistSensor_SteelCompleted(this, new GetlistSensor_SteelCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetlistSensor_SteelAsync(int Id_Sensors, int Id_Steel) {
            this.GetlistSensor_SteelAsync(Id_Sensors, Id_Steel, null);
        }
        
        public void GetlistSensor_SteelAsync(int Id_Sensors, int Id_Steel, object userState) {
            if ((this.onBeginGetlistSensor_SteelDelegate == null)) {
                this.onBeginGetlistSensor_SteelDelegate = new BeginOperationDelegate(this.OnBeginGetlistSensor_Steel);
            }
            if ((this.onEndGetlistSensor_SteelDelegate == null)) {
                this.onEndGetlistSensor_SteelDelegate = new EndOperationDelegate(this.OnEndGetlistSensor_Steel);
            }
            if ((this.onGetlistSensor_SteelCompletedDelegate == null)) {
                this.onGetlistSensor_SteelCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetlistSensor_SteelCompleted);
            }
            base.InvokeAsync(this.onBeginGetlistSensor_SteelDelegate, new object[] {
                        Id_Sensors,
                        Id_Steel}, this.onEndGetlistSensor_SteelDelegate, this.onGetlistSensor_SteelCompletedDelegate, userState);
        }
    }
}
